### ISSUE TITLE
https://github.com/senecajs/seneca-examples goes to 404

### ISSUE THREAD

**Issue by basharov** [senecajs/senecajs.org#102]
Link to samples page on `/tutorials` page shows 404 on Github.

**Comment by bluepuma77** [comment]
"Seneca examples
For convenience, we have a number of sample apps in a single repository. This repository covers single concepts as well as popular plugins. See the repo at Seneca samples."

http://senecajs.org/tutorials/

But the repository seems to be gone: https://github.com/senecajs/seneca-examples
