### ISSUE TITLE
Api page broken link

### ISSUE THREAD

**Issue by AdrieanKhisbe** [senecajs/senecajs.org#112]
Where should they point?
- http://senecajs.org/entity-canon-format
- http://senecajs.org/api/desc-pin-pattern-format

(i'll fix it and make a PR :))

**Comment by geek** [comment]
Can you remove the links for now?

**Comment by AdrieanKhisbe** [comment]
will do :)

**Comment by AdrieanKhisbe** [comment]
done :)
