### ISSUE TITLE
Seneca example in FinTech

### ISSUE THREAD

**Issue by kmworner** [senecajs/senecajs.org#113]
We have release a sample Foreign Exchange trading platform to our [GitHub ] (https://github.com/thecitysecretltd/Lumen-FX) and it makes full use of Seneca. Links to the live demo are on our [website] (http://www.thecitysecret.com/lumenfx)

thecitysecret ltd

**Comment by mcdonnelldean** [comment]
@rjrodger Have you seen this? @kmworner This is epic! I'll need a few days to get through it :D

**Comment by mcdonnelldean** [comment]
CC @geek

**Comment by mcdonnelldean** [comment]
@kmworner Could you provide your logo? We would be more than happy to pop it up on the website. If you have an SVG that would be epic but I can work with anything.

**Comment by kmworner** [comment]
![logo hires](https://cloud.githubusercontent.com/assets/11629238/11692409/368f2a20-9e97-11e5-99bf-4d9bb7dc84ea.jpg)
![logo](https://cloud.githubusercontent.com/assets/11629238/11692410/36a6845e-9e97-11e5-919b-112bcb7a90e3.png)

I hope these logos give you some options, I also have tiff and psd but they are on the large side.

**Comment by mcdonnelldean** [comment]
I might grab the tiff and psd off you to make sure it looks it's best. Could you ping me at dean.mcdonnell[at]nearform.com. I'd like to talk more about your system :D

For now I'm going to pull it down and kick it's tires. We have a couple of OSS projects to support microservices that I'd like to run it against to see how they match up.

Truly epic stuff though, it's very impressive!

**Comment by mcdonnelldean** [comment]
@AdrieanKhisbe If I upload the resources for this (I got them by mail) Could you handle getting the logo up? I'm flat out of time :(

**Comment by AdrieanKhisbe** [comment]
yep, where should it go?

**Comment by mcdonnelldean** [comment]
Front page in the logo section. I'll added the logo to the files in about 30 mins and ping you when it's available. Your a star!

**Comment by mcdonnelldean** [comment]
@AdrieanKhisbe We should probably put a link the example done by @kmworner on our examples page too!

**Comment by AdrieanKhisbe** [comment]
okey dokey
(you can ping me on gitter :) )

**Comment by AdrieanKhisbe** [comment]
@mcdonnelldean, done with a8afec0 ;)

**Comment by AdrieanKhisbe** [comment]
online, closing :)

**Comment by mcdonnelldean** [comment]
Good job!
