### ISSUE TITLE
Prioritarise Documentation Need

### ISSUE THREAD

**Issue by AdrieanKhisbe** [senecajs/senecajs.org#123]
Many Documentation guide have to be written.

Might be a good idea to determine which one are the most urgent so that we focus our attention on tehm.
Idea would be to mark them with a dedicated label, after we identify them with a discussion.

(tags to distingate between: core, user(use seneca), contributor(extend seneca), guide, tutorial might also be usefull)

> What do you think?
@geek @rjrodger

**Comment by AdrieanKhisbe** [comment]
And identify some **milestones** could be a good idea too.!

**Comment by mcdonnelldean** [comment]
@AdrieanKhisbe Agreed! Do you want to kick this off being a user? I want to see what your thoughts are on this.

**Comment by AdrieanKhisbe** [comment]
why not :)
Will draft this on paper, and come up with a milestone proposal later in the afternoon

**Comment by mcdonnelldean** [comment]
Perfect!

**Comment by AdrieanKhisbe** [comment]
*So here is the plan* :)

The three step:

+ Core documentation 
  - API #65 
  - Pin documentation format #111 
  - Data entity query syntax #53 
  - Build store #72 

+ Feature plugins
  - review user, account, web, etc with the *to be* action documentation syntax
  - make doc for account, settings and project

+ Guides and Tutorial
   #11  #94  #93 #52 #14 #9 #10

--------

Also, aside some tasks:
+ Minor linking
  - link to examples
  - link to getting-starte repo
+ Major server doc extension
  - *embed `contrib pages`*
  - embedded plugin README


What do you think about this @mcdonnelldean and @all? :)

**Comment by mcdonnelldean** [comment]
@AdrieanKhisbe Looks good,

I would probably drop the pin stuff as we are looking to depreciate it. I'd rather focus on the others. Apart from that though it looks like a solid order.

**Comment by AdrieanKhisbe** [comment]
@mcdonnelldean  I'm gonna then create the milestone :)

About the pin, is there some issue with the option to depreciate it ? To see the motivations.

**Comment by blainsmith** [comment]
![](http://33.media.tumblr.com/ef933ec5397f1f53077fd89adfba19f2/tumblr_inline_nf3fnhnRIX1r9z4pa.gif)

**Comment by paolochiodi** [comment]
@AdrieanKhisbe @mcdonnelldean I've previously worked on three of the core guides but at the moment I'm unable to complete any of them because I've run out of time.
I'll try to use a couple of nights to organise and share the notes I took for myself while working on #65.
I've also recently updated the seneca-store-test, so I have a good knowledge for #53.

What is your desired timeline for the documentation?

**Comment by mcdonnelldean** [comment]
@paolochiodi I'd just drop whatever you have done into https://github.com/senecajs/senecajs.org/tree/master/src/pages/drafts. We can get them finished then.

**Comment by AdrieanKhisbe** [comment]
thanks @paolochiodi ! :)

by *desired timeline*, you mean to share your notes? or writing for #53 or #65 ?

**Comment by paolochiodi** [comment]
I originally meant for #53 and #65. i.e.: if end of December works for you I can spend some time during the holidays and may be able to complete at least one of the two.
If you need it quicker I'll try to share my notes before Christmas.

**Comment by AdrieanKhisbe** [comment]
end of december is totalluy good for me :)
With this issue, I was just try that we agree on which documentation should be completed first.

**Comment by AdrieanKhisbe** [comment]
@mcdonnelldean @paolochiodi, just created the milestones, and dispatched the issues.
any feedback is welcome :)

**Comment by AdrieanKhisbe** [comment]
milestines created, no feedback so far. closing the issue then. :)

Let's Doc&Roll

**Comment by AdrieanKhisbe** [comment]
Happy new year @paolochiodi :smiley: 
Did you had to devote to documentation?

**Comment by paolochiodi** [comment]
@AdrieanKhisbe sorry, as you may have guessed I didn't have time and neglected this issue.
Unfortunately if I have to be honest I don't know how much time I'll have in the near future to work on this. Maybe it's a better idea to leave this free for others to pick

**Comment by AdrieanKhisbe** [comment]
I undestand. 

Do what you can. :)
You can saw me the raw notes and draft if you want.

_Courge!_

**Comment by paolochiodi** [comment]
I realside most of the notes are already public.
This is obviously the starting point https://github.com/senecajs/seneca/blob/master/doc/data-store.md, then there are a number of issues that I opened to clarify some of the behaviour:
- https://github.com/senecajs/seneca-store-test/issues/20
- https://github.com/senecajs/seneca-store-test/issues/17
- https://github.com/senecajs/seneca-store-test/issues/16
- https://github.com/senecajs/seneca-store-test/issues/15
- https://github.com/senecajs/seneca-store-test/issues/14
- https://github.com/senecajs/seneca-store-test/issues/13

As a result, the seneca-store-test should be now collecting the correct behaviour.

Also worth of pointing out this PR: https://github.com/senecajs/seneca-store-test/pull/29 that will add support for a broader set of queries

**Comment by AdrieanKhisbe** [comment]
Thanks @paolochiodi, that's really helpfull and time saving.

_courage!_

**Comment by paolochiodi** [comment]
Fill free to ping me if you need clarification on any issue

**Comment by AdrieanKhisbe** [comment]
nopro :) (might not come right away ;) )
