### ISSUE TITLE
Plugin Specific Docs

### ISSUE THREAD

**Issue by blainsmith** [senecajs/senecajs.org#130]
Some of the README.md files have references their local `docs` folder, but the repo references are old and need to be updated. However, since they now live under the senecajs org that does not have a GitHub Pages set up so even the new locations don't work.

http://senecajs.github.io/seneca-level-store/doc/level-store.html

I think we someone just needs to setup GitHub Pages for the senecajs org for these to work unless we want to host them elsewhere.

**Comment by mcdonnelldean** [comment]
@blainsmith Can you clarify?

Throw me some examples?

The docs (this site) is hosted via surge.sh (it gets published every time master changes). If the doc exists on senecajs.org the readmes need to be updated to point there (we can open issues).

**Comment by blainsmith** [comment]
For the level store is is the content within https://github.com/senecajs/seneca-level-store/tree/master/doc that used be accessible via http://rjrodger.github.io/seneca-level-store/doc/level-store.html, but once it was moved to the senecajs org they stopped working.

**Comment by mcdonnelldean** [comment]
All docs are going to be moved out of their respective repos soon and added to the website where it makes sense to do so. Other information will be disseminated into respective readmes.
