### ISSUE TITLE
Merge /Contrib

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/senecajs.org#132]
We have agreed to merge /contrib into this lib.

I think we should also,

- Update the readme of this repo to point to the markdown docs ala contrib
- Ensure the readme states this is the place for all needs previously assigned to /contrib

**Comment by mcdonnelldean** [comment]
Boo! Only one person can be assigned to an issue... Thats pants of the highest order

**Comment by geek** [comment]
@mcdonnelldean hehe, thats a new one to me... what does pants of the highest order mean?

**Comment by AdrieanKhisbe** [comment]
does it even mean something? :jeans:  ^^

**Comment by mcdonnelldean** [comment]
@geek Pants is a way to say boll*cks when kids are around :D

**Comment by geek** [comment]
Glad I asked :)  I am writing this down in my book, "How to cuss around kids"

**Comment by AdrieanKhisbe** [comment]
what remains to be done before closing the issue?

**Comment by geek** [comment]
Contrib is now deleted... we will want to review links on the site to make sure we don't have anything going to the contrib repo

**Comment by AdrieanKhisbe** [comment]
@geek what happened to its issues?

**Comment by geek** [comment]
@AdrieanKhisbe they were outdated issues I opened a while back... I almost moved them over to discuss... but they won't be missed.

**Comment by AdrieanKhisbe** [comment]
has long as migration takes place! :)
