### ISSUE TITLE
Documentation pages for seneca tools

### ISSUE THREAD

**Issue by AdrieanKhisbe** [senecajs/senecajs.org#134]
Was considering a page, or set of pages with docs/tuto for a lot of tools underlying seneca.

Most of them from @rjrodger such as jsonic, patrun, parambulator, eraro, tagx, gex

What do you think??

**Comment by geek** [comment]
I like this idea.  We could enhance our `/API` page to have child contents, like you did for contribute.  Thoughts?

**Comment by AdrieanKhisbe** [comment]
not yet (sleepy mind), but one remark:

We should make the distinction clear between the *seneca api* (lib api), the *seneca actions* (microservices api)

**Comment by AdrieanKhisbe** [comment]
I think it should be similar to what hapi will take as option to document the plugins.
(apiaction doc belongs in the respective plugin repositery)

though one problem is that contrary to hapijs.com, senecajs.org is statically generated website

**Comment by AdrieanKhisbe** [comment]
Mmmm, look what I stumble on: 
https://github.com/geek/metalsmith-download

:D
