### ISSUE TITLE
Suggestion: Stability badges?

### ISSUE THREAD

**Issue by AdrieanKhisbe** [senecajs/senecajs.org#142]
Shall we use Stability badges to flag seneca-plugin stability
https://www.npmjs.com/package/stability-badges

![experimental](http://hughsk.github.io/stability-badges/dist/experimental.svg)
![unstable](http://hughsk.github.io/stability-badges/dist/unstable.svg)

**Motivation:** so far we have on seneca.js plugin that are in very different state of maturity. some still draft, some more matured.
Would be a good way to express that.

@senecajs/contributors What do you thinks guys&ladies?

**Comment by mcdonnelldean** [comment]
@senecajs/contributors I'm happy to do this as long as it links to a doc explaining our definitions of each stability. It would make looking for work easier too.

**Comment by AdrieanKhisbe** [comment]
@mcdonnelldean  :+1: :smiley:

**Comment by geek** [comment]
We should do this.  We just need to update our http://senecajs.org/contribute/details/guidelines.html to detail the different badges.  I vote just having stable and unstable, what do others think?

**Comment by mcdonnelldean** [comment]
We are planning to bring this in for 3.0 but with different badges that align better to plugin based modules over framework based modules.
