### ISSUE TITLE
Documentation: Add a CONTRIBUTING.md to the base of seneca projects

### ISSUE THREAD

**Issue by thekemkid** [senecajs/senecajs.org#144]
Started already with this PR: https://github.com/senecajs/seneca/pull/292

And mentioned why in this PR: https://github.com/senecajs/senecajs.org/pull/143

If we start adding a CONTRIBUTING.md to the base of every project, we will have the contribution guidelines pop up when people attempt to create a PR. Pretty nifty. I got the idea when talking to @geek.

**Comment by thekemkid** [comment]
cc @senecajs/contributors

**Comment by AdrieanKhisbe** [comment]
I'm thinking it would be a good thing to agree to standardize how a plugin should be in term of README:

- badges, header, structure
- Api documentation. (file and format)
- contributing.md
- other config: .eslintrc, .npmigno, gitignore, travis
- License

**Comment by thekemkid** [comment]
We also need to standardise the lead maintainer, the package.json, and the how npm is maintained. Are we just supposed to npm publish modules we maintain? how do we aggregate our npm modules? Just some extra thoughts.

**Comment by AdrieanKhisbe** [comment]
exactly :)

**Comment by geek** [comment]
@thekemkid if you have publish rights then I would say you can publish any module you have access to at any time that you see fit.

The lead maintainer should be at the top of the module readme.  I vote we leave it up to the maintainer to decide on how they add authors and contributors to the package.json.

**Comment by thekemkid** [comment]
README Standardisation:

```markdown
![Logo][]
# Header

### Tagline/one line description
Badges = [npm, travis, coverage, dependencies, seneca gitter badge]

About (around a paragraph)

-  lead maintainer/s
- Expected node compatibility

## Example

A quick example of this in use.

For more examples, please check the /examples folder. (organise examples by folder, and give each folder a readme.md)

## API

Generally, I go with MDN style api documentation, which might work in the form:

seneca.act(pattern1, cb)
pattern1 expected input:
- foo (string): a string to represent foo
- bar (string)*: a string to represent bar

seneca.act(pattern2, cb)
pattern3 expected input:
- zed (string): a number to represent zed

where * represents optional pattern properties

## contributing
We welcome all contributions....
check our CONTRIBUTING.md
check out indepth contrib guide

## License

[Mit](./license) copyright author and other contributors

[Logo]:http://senecajs.org/files/assets/seneca-logo.png
```

**Comment by thekemkid** [comment]
Example CONTRIBUTING.md

```markdown
# How to contribute
We welcome contributions from the community and are pleased to have them.  
Please follow this guide when logging issues or making code changes. If unsure
about anything, you can refer to our
[indepth contributing guidelines here][contribGuidelines].

## Logging Issues
All issues should be created using the [new issue form][newIssue].  Clearly
describe the issue including steps to reproduce if there are any.  Also, make
sure to indicate the earliest version that has the issue being reported.

## Patching Code
Code changes are welcome and should follow the guidelines below.

* Fork the repository on GitHub.
* Fix the issue ensuring that your code follows the [style guide][styleGuide].
* Add tests for your new code ensuring that it is fully tested.
* [Pull requests][pr] should be made to the [master branch]().

[Adapted with permission from Hapijs.](https://github.com/hapijs/hapi/)

[newIssue]: https://github.com/senecajs/seneca-fire-and-forget/issues/new
[styleGuide]: http://senecajs.org/contribute/details/styleguide.html
[contribGuidelines]: http://senecajs.org/contribute/
[pr]: http://help.github.com/send-pull-requests/
[master]: https://github.com/senecajs/seneca-fire-and-forget/tree/master
```

**Comment by thekemkid** [comment]
I edited the contrib.md from seneca core for use in other non-core repos (above). The main difference is the removal of the requirement to add coverage tests for new features. If needed, we can advise to add them per PR, or the contrib.md could be modified back to put that in, depending on the maintainer :)

**Comment by AdrieanKhisbe** [comment]
@thekemkid 
Could you create a repositery for that? That would be better for discussion and incremental tweaking  :)
(I can do it if your prefer)

**Comment by thekemkid** [comment]
I can do it later :)

**Comment by AdrieanKhisbe** [comment]
:+1:  :smiley: 
Ping me when you'll have started ;)

**Comment by thekemkid** [comment]
Pew, Pew Pew: https://github.com/thekemkid/seneca-standardised-repo
We can pr and issues stuff over here :)

**Comment by AdrieanKhisbe** [comment]
PRs incomning

**Comment by AdrieanKhisbe** [comment]
One question though.
Shall we discuss standard here and apply there, 
or discuss directly on repo??

(we should move it to senecajs as soon as we can :) )

**Comment by thekemkid** [comment]
We have this issue open, so we can discuss here, but, any suggested changes could simply be made in PR's, and discussed on the relevant PR. We could link to the individual PR's here, so there is a trail for anyone that tries to follow this issue.

I can transfer the repo to senecajs now, if you like :)

**Comment by mcdonnelldean** [comment]
Be careful here folks, as @geek says Lead maintainer can decide individual style, we can certainly have this as a guide but I'm against enforcing this level consistency. It never ends well.

**Comment by mcdonnelldean** [comment]
The style as it is has pretty much become standard. Closing to do relevance.
