### ISSUE TITLE
Missing logos

### ISSUE THREAD

**Issue by mihaidma** [senecajs/senecajs.org#145]
on http://senecajs.org/ there are logo images missing or links broken

**Comment by AdrieanKhisbe** [comment]
For some obscure reason, svg service is broken:

http://senecajs.org/images/tcs-logo.svg
![broken](http://senecajs.org/images/tcs-logo.svg)

**Comment by mcdonnelldean** [comment]
That's really odd? Is it for all svg's?

**Comment by AdrieanKhisbe** [comment]
looks like that.
The two broken logo are the svg ones. (all other are png)

**Comment by mcdonnelldean** [comment]
Really Odd.. Any opinions?

**Comment by AdrieanKhisbe** [comment]
except that `svg` racism, I don't see ^^

**Comment by AdrieanKhisbe** [comment]
seems to come from metalsmith.
Tested locally on my machine adding another svg.

Issue poster: cf https://github.com/metalsmith/metalsmith/issues/209

**Comment by AdrieanKhisbe** [comment]
Fixed by b7974cb

**Comment by AdrieanKhisbe** [comment]
And live. Closing
