### ISSUE TITLE
Contribute page broken links

### ISSUE THREAD

**Issue by mihaidma** [senecajs/senecajs.org#146]
Most of the links are broken:

https://github.com/senecajs/senecajs.org/blob/master/src/pages/contribute/index.md

**Comment by AdrieanKhisbe** [comment]
Merging #143 should do the trick

**Comment by AdrieanKhisbe** [comment]
Would have to look if @metalsmith takes care to convert `.md` links to `.html`

**Comment by mihaidma** [comment]
can we prevent this from happening again?

**Comment by AdrieanKhisbe** [comment]
What do you mean?

Setting a broken link checker?

This happened because we move the whole contrib repo under senecajs.org pages. So theoriticaly this exact cause wont occur anymore

**Comment by mcdonnelldean** [comment]
Broken link checker would do no harm all the same? It would be nice if .md where auto changed too.

**Comment by mihaidma** [comment]
I mean I see a whole chain of issues: someone PRed something broken, the broken stuff got merged, the merged stuff got published, the broken changes stayed unnoticed.

We should enhance the process.

Let me disagree: theoretically it will happen again :)

**Comment by mcdonnelldean** [comment]
I agree with @mihaidma. This issue will come up over and over, we should guard against it. I know there are some metalsmith plugins that will throw on failure, we need to look at things like this.

**Comment by AdrieanKhisbe** [comment]
And I do agree too.
I just meant that broken link would not probably come from ingesting another repo.
But for sure they'll come from other reasons :)

I'll check how to set up https://github.com/davidxmoody/metalsmith-broken-link-checker

**Comment by AdrieanKhisbe** [comment]
@mcdonnelldean @mihaidma :
Do you agree I close this and create a *setup link check* issue?

**Comment by mcdonnelldean** [comment]
Sure
