### ISSUE TITLE
Implement LESS to simplify CSS management

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/senecajs.org#149]
@AdrieanKhisbe I agree we need something here.

However, I want to avoid SCSS because of it's learning curve. While I appreciate it's not a particularly large curve one of the strict instructions for this project is keep it beginner simple, we want this to be a place people can make their first contributions. We need to very carefully balance our contribution complexity vs our needs.

Really the only main requirements I see are

- Variables for coloring and theming
- Ability to split into separate files.

Although Less has other features I'd really like to keep our CSS as simple as possible (although I'm not opposed to things like auto prefixes)

**Comment by AdrieanKhisbe** [comment]
Why do you say scss has a tougher learning curve than less?
(said scss since I was a bit more familiar, and seemed like it had won the beauty contest)

Totally agree for the requirements. (would just add to have `darker(color, percent)`

**Comment by AdrieanKhisbe** [comment]
Here would be the plugins:

- https://github.com/christophercliff/metalsmith-less (3 stars, 3 contributors, ,37 commits)
- https://github.com/stevenschobert/metalsmith-sass (19 stars, 8 contrinutors, 70 commits)

**Comment by mcdonnelldean** [comment]
Sass has far more power, people tend to want to use it when available. This leads to complicated CSS and makes it harder for someone who only has CSS as their knowledge.

**Comment by AdrieanKhisbe** [comment]
I see. and Understand.
and Less had the function I wanted: http://lesscss.org/functions/#color-operations-darken

So it's perfect :)

**Comment by ckiss** [comment]
@mcdonnelldean @AdrieanKhisbe I don't think the learning curve of any of sass or less should be a no go here :) If people don't know any of them(which I don't think is the case) they can still write plain CSS in those files, right?

**Comment by mcdonnelldean** [comment]
Looking around, it does seem sass has moved more to looking like CSS as much as possible.

I also see SASS really is leading the charge. Hmm, ok lets go with Sass but keep it simple @AdrieanKhisbe

**Comment by AdrieanKhisbe** [comment]
Roger that :D

Was waiting for my ci bump to be merge into metalsmith-less before doing the operation

**Comment by AdrieanKhisbe** [comment]
on progress there:
https://github.com/AdrieanKhisbe/senecajs.org/tree/setup-scss

So far just set up. and applied netsing.
then extract color into variables
