### ISSUE TITLE
Write a responsible disclosure policy

### ISSUE THREAD

**Issue by AdrieanKhisbe** [senecajs/senecajs.org#153]
Here is a suggestion from [an article](https://kev.inburke.com/kevin/dont-use-sails-or-waterline/) I ended up reading while unstaking my tab article on OSS projects

> If I find a critical vulnerability in Sails how should I communicate it to the core team?
- What guarantees are given about time to a patch?
- Will reporters be credited for their work in finding a vulnerability?
- How are critical security vulnerabilities disclosed to the community?
- Are vulnerabilities given a CVE number?
- Once you write a page like this, how can I be expected to find it?

> Here is an example of what a page like this should look like: http://docs.python-requests.org/en/latest/community/vulnerabilities/

cf (https://github.com/balderdashy/sails/issues/2830)

@senecajs/core & @senecajs/contributors, what do you think about this?

**Comment by mcollina** [comment]
I think we should just point people to https://nodesecurity.io. Also, we should run https://www.npmjs.com/package/nsp as a prepublish script, just to make sure everything is ok on our side.

**Comment by AdrieanKhisbe** [comment]
:+1: for running `nsp` !

And good idea for pointing to nodesecurity. Perfect *ratio effort/effect*

where do you think we should put it on the website/[repo](https://github.com/senecajs/senecajs.org)?

**Comment by mcollina** [comment]
I think we should put it in the project/subprojects readme. As for the
website, we should possibly put it into its own page, but I'll leave that
decision to the others.
Il giorno lun 11 gen 2016 alle 11:48 Adrien Becchis <
notifications@github.com> ha scritto:

**Comment by mcdonnelldean** [comment]
@AdrieanKhisbe I'd like to talk to @rjrodger about this before we make any decisions.

**Comment by AdrieanKhisbe** [comment]
@mcdonnelldean No problem :)

Was just raising up the subject :smiley:

**Comment by geek** [comment]
Love supporting security researchers.  We can model after the node security page: https://nodejs.org/en/security/  I am sure @evilpacket will be happy that we have one.

**Comment by evilpacket** [comment]
This is rad. Great initiative.

If it's a sub dependency nsp should be a good go to to catch it on ci or a hook of some kind. 

It would still be good to document your intentions with things that directly effect the main project or modules that you maintain of it.

Anything you can document on the project as to the following is good.
- how to report vulnerabilities (is it an email address, do you want them to cc the node security project?)
- how those will be handled (timelines, communication, etc)
 
The biggest frustration for a security researcher is to not know where to send vuln reports and not have an expectation as to fixes.

Couple examples of a security.md from other projects that you might find useful.
- https://github.com/reddit/reddit/blob/master/SECURITY.md
- https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/release/security.md
- https://github.com/discourse/discourse/blob/master/docs/SECURITY.md

**Comment by AdrieanKhisbe** [comment]
thanks @evilpacket for these pieces of advice! :smiley: 

@geek shall we add one Security only to seneca and senecajs.org, 
or in each plugins? (in that case, we would have to add them to the in building seneca cocktail of #144)

**Comment by mcdonnelldean** [comment]
A SECURITY.md and an nsp check are to be added to all golden circle repos. This will be done for the 3.x launch later this month.

**Comment by evilpacket** [comment]
I will do a freak'n dance if you add anything related to communicating how security issues are handled :) /jig
