### ISSUE TITLE
"Beat Your Manager" links to undesirable page

### ISSUE THREAD

**Issue by lionpants** [senecajs/senecajs.org#155]
The "Beat Your Manager" image under the "Who uses Seneca" section links to... lets just say; not what I was expecting. :-P

Looks like its the correct URL, but the owners lost the domain or something.

**WARNING**: NSFW, which is unfortunately where I found this problem.

![screen shot 2016-01-11 at 1 42 31 pm](https://cloud.githubusercontent.com/assets/4184468/12242846/63bf1a5a-b869-11e5-9c1d-631ca3d840ec.png)

**Comment by AdrieanKhisbe** [comment]
Indeed Indeed... 

I see three possible course of action:

- replace link to point to appstore.
- disable link for now
- remove beat your manager.

@mcdonnelldean. what's your mind?

**Comment by thekemkid** [comment]
I wonder if they're using seneca? :laughing:

**Comment by padraigbdoolan** [comment]
Hi guys, I'm the owner of that domain - this definitely is not our doing and we are working now to rectify the situation. Thanks for notifying us

**Comment by thekemkid** [comment]
Drop a comment here when fixed & we'll revert the commit :)

Cheers,
Glen

**Comment by AdrieanKhisbe** [comment]
@thekemkid :+1:

**Comment by padraigbdoolan** [comment]
Hi everyone, we have taken the site down while we deal with this - apologies to anyone who clicked on the link

**Comment by padraigbdoolan** [comment]
Will do, cheers!
