### ISSUE TITLE
 Proposal to Improve the communication between contributors.

### ISSUE THREAD

**Issue by AdrieanKhisbe** [senecajs/senecajs.org#158]
Seneca.js is becoming more and more active, and I'm sure it will go further after yesterday release.
Also new contributors have join the team!   \o/ 
Effective Communication between @senecajs/contributors is getting more and more important.

To do that, we use mainly two channels:
- On specific subjects/issuest: the **github issues**, that are more and more used.
- Interactive live communication between contributors: to do that we use **gitter** to some extent.

We are doing great, but we could improve even more:
To do so I suggest to *use senecajs.org gitter for inner team communication, collaborators while keeping gitter for communication of seneca users and community*.

So So, Shall we begin? :)
@senecajs/core @senecajs/contributors

**Comment by mihaidma** [comment]
:+1: I also feel the need to communicate and be able to synchronize with other team members. The public gitter would be ok-ish for most topics.

**Comment by AdrieanKhisbe** [comment]
the two gitter will stay public.
What I see on gitter is there is collision, and interference of discussion of intern collaborator discussion and extern users&community discussions.

Hence the opening of a second gitter, this one specialized on contributing. ;)

**Comment by mcollina** [comment]
I'm :+1: on these. Also, we should probably set up a biweekly/monthly call with contributors, just to discuss the direction of the project.

**Comment by AdrieanKhisbe** [comment]
@mcollina. Excellent Idea!!!  :tada:

**Comment by thekemkid** [comment]
We will (obviously) need to keep notes of any notable discussions or decisions made on gitter. Github issues is obviously the best way of conveying this info. 

Any organisational discussions/decisions about repos/structures, etc, should they be logged as issues on this repo, or on the core seneca repo?

For example, when we finalise some form of standard structure for repos & readmes (for issue #143), should we open an issue with the plan _here_ or on _seneca_ itself? I'm inclined to believe it should be here, as that appears to be our current approach. :)

**Comment by AdrieanKhisbe** [comment]
So @senecajs/core and @senecajs/contributors, let's go and open this channel?

**Comment by AdrieanKhisbe** [comment]
> $ TOUCH THIS

(Or we can use the senecajs organisation: but it's less open: https://gitter.im/senecajs)

**Comment by AdrianRossouw** [comment]
https://gitter.zendesk.com/hc/en-us/articles/200178951-Gitter-rooms

> Finally, channels allow you to create arbitrary rooms that don't map directly to an entity on GitHub. For example you may wish to your create YourOrg/chat as a public chat room. Channels can be public, private or inherit GitHub owner permissions.If you click on the Create a room button on the bottom left of the screen, you should easily be able to create a channel. Please note that you will need to be on one of our paid plans to create a private channel.

So what do we want to call the channel?

**Comment by mcdonnelldean** [comment]
@senecajs/contributors have agreed to move comms to gitter, this is where the community seems to be anyway. @AdrianRossouw has started the process of asking how we break down the work with various members of the community since it's best to get feedback from them.

**Comment by AdrieanKhisbe** [comment]
ACK :disappointed:
