### ISSUE TITLE
Ecosystem Trello Board

### ISSUE THREAD

**Issue by AdrieanKhisbe** [senecajs/senecajs.org#159]
##### Here is a proposal to have a trello board to have a quick overview of the whole *seneca* ecosystem.

Here is how this would be organised:

- **List** are used to capture the differents categories, Cards represent the differents plugins and co.
- ***Labels**
  + So far I used label to capture the status of the plugin, cf #42. Using the same color.
  + Some extra label were added to represent action that need to be done (with a `->` prefix). Ex: Doc, Ci, and Focus.
  + And `community` for repo that are not host under organisation.
  + Maybe might be better not to use all color for Maintenance status. and have it for stuff like *Review Needed*, *Dependency Upgrade*, *Security*.

+ The Idea is also that each mainteners are attached to the cards.

Here is the draft of what it would look like: https://trello.com/b/gr5agWi3/seneca-ecosystem
The maintenance status have not yet been applied, and obviously, I haven't done all the card yet.
**Waiting to hear what you @senecajs/contributors  think.**

> Voili Voilà Voilou =)

**Comment by AdrieanKhisbe** [comment]
> $ touch @senecajs/core @senecajs/contributors 

? :smiley:

**Comment by thekemkid** [comment]
No reply means no complaints: +1 From me :+1:

**Comment by mihaidma** [comment]
@geek started a shared gdoc a while ago. Should we move that to a public trello?

**Comment by mcdonnelldean** [comment]
@geek I think this is a nice alternative to the gDoc.

**Comment by AdrieanKhisbe** [comment]
Since it seems to receive positive feedback, I started to incrementaly build it

**Comment by geek** [comment]
I am supportive of anything that helps people find out what the state of our system is.  I really wish that Github had better organization tooling to handle issues.  

Do you all think we need trello instead of relying on https://github.com/orgs/senecajs/dashboard only?

**Comment by cjihrig** [comment]
> I really wish that Github had better organization tooling to handle issues.

You could try adding your name to https://github.com/dear-github/dear-github

**Comment by geek** [comment]
@cjihrig thanks... signed!

**Comment by thekemkid** [comment]
Tbh, I forgot about the dashboard. I think a trello board might be a better choice (right now.)

**Comment by AdrieanKhisbe** [comment]
@senecajs/contributors  
Any feedback so far?

**Comment by mcdonnelldean** [comment]
@AdrieanKhisbe Is this and #171 The same thing?

**Comment by AdrieanKhisbe** [comment]
@mcdonnelldean Nopi Nope.

**Comment by AdrieanKhisbe** [comment]
Switching off a patient's life support 🔌

**Comment by AdrieanKhisbe** [comment]
_closed board :arrow_forward: closed issue_
