### ISSUE TITLE
Document transport `path` param.

### ISSUE THREAD

**Issue by thekemkid** [senecajs/senecajs.org#160]
Did you know, that when calling `.listen(options)` on a seneca instance, you may provide a path property to the options parameter when using web/http? I didn't.

To revise, you may create your listener like so:

``` javascript
seneca.listen({
  host: '0.0.0.0',
  port: 10101,
  path: '/act',
  type: 'web'
})
```

(I provided the defaults for `type: 'web'` above, so by default the `path` is '/act', try it :smile:)

You can hit then hit a uri ("http://host:port/path") externally with `'Content-Type': 'application/json',` to get a reply. (in json form, obviously).

By documenting this, we can show people how to get their services/libraries communicating from non-seneca instances, which opens up a doorway to creating seneca ports in other languages.

**Comment by AdrieanKhisbe** [comment]
:+1: GREAT @thekemkid
