### ISSUE TITLE
Move to Chakra's more explicit code of conduct

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/senecajs.org#161]
I want to move to Chakra's more explicit code of conduct as it better describes how the lead maintainers feel about our contributors. I also think the code of conduct should be reproduced, like the license within the contribute page itself.

- [Chakra CoC](https://github.com/Microsoft/ChakraCore/blob/master/CODE_OF_CONDUCT.md)

**Comment by AdrieanKhisbe** [comment]
Which relevant section in particular do you think. We could incorportae to existing one: 

https://github.com/senecajs/senecajs.org/blob/master/src/pages/contribute/details/code-of-conduct.md

An alternative to replication. would be that on each README, we have a badge pointing to the code of conduct
[![CC](https://img.shields.io/badge/code_of_conduct-open,civilized&respectful-379199.svg)](better describes how the lead maintainers feel about our contributors)

**Comment by mcdonnelldean** [comment]
I'd rather fully replace, nice to stick with standards. Love the idea of the badge. Can we have spaces between the , and &? I would like this in addition to the replication. I want us to be explicit in our commitment.

**Comment by thekemkid** [comment]
I dislike the ambiguity of `to ban temporarily or permanently any contributor for other behaviors that they deem inappropriate, threatening, offensive, or harmful`

**Comment by mcdonnelldean** [comment]
Bans can always be peer reviewed in the interest of fairness and the reality is bans would be closely monitored by all lead maintainers, at the very least by Myself, @geek, @rjrodger or @mcollina. @AdrieanKhisbe and yourself also know what is and isn't obviously harmful behaviour, your good people. The reality they will not be a common occurrence.

I don't want to kick off a debate on the wording, the CoC's primary purpose is to ensure contributors are aware of our commitment to their safety. This CoC has been broadly accepted and is explicit in it's language where necessary and it's intent otherwise.

**Comment by AdrieanKhisbe** [comment]
About the badge:

[![CC](https://img.shields.io/badge/code_of_conduct-open,_civilized_&_respectful-379199.svg)](https://github.com/senecajs/senecajs.org/blob/master/src/pages/contribute/details/code-of-conduct.md)
 
Code source:
```markdown
[![CC](https://img.shields.io/badge/code_of_conduct-open,_civilized_&_respectful-379199.svg)](https://github.com/senecajs/senecajs.org/blob/master/src/pages/contribute/details/code-of-conduct.md)
``` 

but has a side note, that was just an example. Should be more consive I think :)

**Comment by AdrieanKhisbe** [comment]
Also, I hadn't reallied it was an emerging standard at first lecture. no I see more the point :)

**Comment by mcdonnelldean** [comment]
@AdrieanKhisbe I like the long one, it's informative without being in your face. There is a little underscore coming up for me after the _. Once that's removed, we are good to go.

**Comment by AdrieanKhisbe** [comment]
This is more a glitch with shields.io

Bye bye ampersand -> [![CC](https://img.shields.io/badge/code_of_conduct-open,_civilized_and_respectful-379199.svg)]

**Comment by thekemkid** [comment]
I don't wanna debate either, too tired for that! :sleepy:

I'm 50/50, on the fence, with the CoC change, so either way, I'm cool and not objecting in any real way :)

**Comment by mcdonnelldean** [comment]
@thekemkid Let's try it out, see how we fare, if it's not working we can always look at alternatives, such is the POWER OF COMMUNITY!
