### ISSUE TITLE
Contribute pages don't have template applied

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/senecajs.org#162]
Looks to be the ones pulled in from /contribute

We should write a metalsmith plugin that checks if a template has been applied before publish and throw an error if we are missing an expected one.

**Comment by AdrieanKhisbe** [comment]
@mcdonnelldean you mean at the top of the file?
If so, no problem, by default it's the main layout that is applied.

**Comment by mcdonnelldean** [comment]
When you navigate to them they aren't styled and look raw.

**Comment by thekemkid** [comment]
yup: http://senecajs.org/contribute/details/styleguide.html

**Comment by AdrieanKhisbe** [comment]
don't know why, default template had disappered from the json config.

Now restrore :)
