### ISSUE TITLE
Document plugin initialisation

### ISSUE THREAD

**Issue by AdrieanKhisbe** [senecajs/senecajs.org#164]
In plugin tutorial, plugin initialisation is mention, but not yet documented

> As with most things in Seneca, you define an action pattern to handle initialization, and make sure it happens in the proper order. We’ll talk about plugin initialization a little later. Many plugins don’t even need to initialize because all they do is define a set of action patterns.

cc @mlequain

**Comment by mcdonnelldean** [comment]
Closing as done.
