### ISSUE TITLE
Stagging website

### ISSUE THREAD

**Issue by AdrieanKhisbe** [senecajs/senecajs.org#166]
While building #165, comes to me the need to have some staging, 
so we could test what the website would look on the world wide web. 

Main benefit is that everyone can see progress and comment on that.
Besides it prevents the *work's on my machine* syndrome.

@mcdonnelldean.
What do you think how that? and how could we set this up?

**Comment by mcdonnelldean** [comment]
@AdrieanKhisbe Let me have a think about how this should work, for now though just sign up to surge.sh, then you can push it to a xyz.surge.sh bucket and see it on the real web.

I would most likely end up doing the following to support staging:

- Add `npm run stage`
- Use `staging.senecajs.org` as the link
- Have maintainers added to the surge acc
- Allow maintainers to run staging manually via npm

**Comment by AdrieanKhisbe** [comment]
Thanks @mcdonnelldean 
Will do but on monday. *Hackathon Oblige :)*

**Comment by mcdonnelldean** [comment]
Enjoy!

**Comment by mcdonnelldean** [comment]
Closing as I found the best is for maintainers to use surge directly, anything else is a maintenance headache, surge is free.
