### ISSUE TITLE
Question: Calling seneca services from other languages?

### ISSUE THREAD

**Issue by n321203** [senecajs/senecajs.org#169]
Hi,
Seneca looks great. 
Has anyone tried calling Seneca services from python or any other (non-node) language? The reason is that I am using github.com/spotify/luigi for background tasks management which is a very good tool but it is written in Python. It would be great to be able to call Seneca services directly from the task scheduler.

I am guessing you have to implement the service discovery mesh plugin in python in order to know where the servers are...?

**Comment by mcdonnelldean** [comment]
You could talk to them directly, if you use the http transport just set your seneca instance up to listen on a specific port and use http to talk to it. I'm out right now but this should give you an idea of what you need. https://github.com/senecajs/seneca-transport#non-seneca-clients I'd love to see some non node clients myself :D

**Comment by thekemkid** [comment]
Maybe this will help: https://github.com/senecajs/senecajs.org/issues/160

Basically, when you tell seneca to .listen, you can provide a path parameter if listening on http.

this path parameter can be hit from any external service with json.  Then seneca will handle the json, send it to the appropriate pattern handler, and send the reply.

Try run this code:
```javascript
var seneca = require('seneca')()
seneca.add({role: 'math', op: 'add', x:'*', y: '*'}, function (args, done) {
     done(null, {result: x+y})
}
seneca.listen({type: 'web', port: '20100', path: '/act'})
```

When that is running you should be able to cURL the service externally, with the following:

```bash
curl -d '{"role": "math", "op": "add", "x":1, "y":6}' http://localhost:10201/act
```

Let me know if you need more help! :)

**Comment by AdrieanKhisbe** [comment]
I'm gonna add some clarification about this in the doc/tuto, waiting for the proper guide:
cf  #10

**Comment by mcdonnelldean** [comment]
@n321203 I'm going to set this to closed as answered, any more q's feel free to reopen :+1:
