### ISSUE TITLE
Lack of detail for the API documentation

### ISSUE THREAD

**Issue by jhyland87** [senecajs/senecajs.org#170]
Minor issue, but I was thinking that the [API Documentation](http://senecajs.org/api/) seems a bit lacking, don't you think? I mean the methods **export, pin, close, client, listen and act** basically just have the method listed, and the arguments they accept, but no detail as to what they actually do.

If I'm reading this wrong, or looking in the wrong place, then I apologize. 

Thanks

**Comment by AdrieanKhisbe** [comment]
I totally agree, it needs to be improve. cf #65.
(you're perfectly in the good place).

With @senecajs/core getting the 1.0, documentation is the more prioritary issue.
I'm going to be watchful about this, but unfortunately can't write the documentation alone. :/

Have a look to [seneca nodeschool workshop](https://github.com/senecajs/seneca-in-practice) if you haven't done it yet :)

(by the way, sorry not having reach out to you on gitter contrary to what I said. far more busy than expected)

**Comment by AdrieanKhisbe** [comment]
Check out  http://senecajs.org/api/ @jhyland87,
@kamil-mech made an **AWESOME** job this weekend :smiley: 

Then considering the issue solved :)

**Comment by kamil-mech** [comment]
@AdrieanKhisbe  You're welcome :)
