### ISSUE TITLE
Going for a more agilistic, kanban style, trello organisation

### ISSUE THREAD

**Issue by AdrieanKhisbe** [senecajs/senecajs.org#171]
Hello @senecajs/core and @senecajs/contibutors

**What I propose is to adopt a more _Kanban Style Organisation_.**
With that it would be better to see what we are working on,
and how we can contribute to help complete the feature that are
almost ready to ship.

Using _labels_, we could distinguish kind of tasks, and also target what are the focus point, the extra feature, ...

Besides, it would enable us to *tweak our process* with our needs. (introducing new columns, label)
Giving us the **flexibility** to be more **efficient**.

<img width="233" alt="capture d ecran 2016-01-21 10 01 27" src="https://cloud.githubusercontent.com/assets/2601132/12476612/e051dd82-c02a-11e5-9ca3-d3da604257e2.png">

Here is the draft: https://trello.com/b/wsf4dgXE/seneca-development

----------
> ### _Feedback Much Welcome!_
> #### _**ACTION** even **MORE !!**_  :smiley:

----------
Some Reading: https://medium.com/cto-school/ditching-scrum-for-kanban-the-best-decision-we-ve-made-as-a-team-cd1167014a6f#.4iamy2b77

Ps: I plan to ask trello is, as a Open Source Project, we could have free access to the entreprise plan, to be able to use integrations

**Comment by mcdonnelldean** [comment]
@AdrieanKhisbe It would be @geek @rjrodger who need to look at this, it would be them working with it on a day to day basis.

**Comment by AdrieanKhisbe** [comment]
Okey.
Waiting for your input @geek and @rjrodger.
Feel free to ask me anything, I'll be pleased to explain the rationale, and whyes. 
> **#SoKanban #MuchKaizen #SoLean #WOW**

**Comment by geek** [comment]
@AdrieanKhisbe thoughts on just using the assignee feature in github and avoiding trello?

**Comment by mcdonnelldean** [comment]
Thats where I'm at on concorda / vidi. Ive even drastically reduced labels and dropped milestones on senecajs.org. Streamlined the whole lot and it works perfect

**Comment by AdrieanKhisbe** [comment]
@geek 
I consider that trello and github issues are complementary.
github issues are not good thing for planning. they are not made for that. -> status, due date, prerequesites and co.
One workaround would be status label, but it's not that handy.

Besides, considering we would attach a trello card to an issue, on trello you can assign several person to a card. and have chatty comment on a card. (comments that don't belong on an issue, that's here to stay forlong).

and then if necessary, when can use an automation tool as ifft to create trello card from the new github issue.

@mcdonnelldean though I agree simplifying label (finer granularity), milestone are good thing to priotarize effort and plan. (reason created them on senecorg)

**Comment by geek** [comment]
@AdrieanKhisbe we can use the milestones in github for planning.  I don't like setting a due date on them though, its more useful as a container of issues you plan to be within a release.

**Comment by AdrieanKhisbe** [comment]
@geek, exactly! :)
there is no such thing as _deadline_ ;)

**Comment by thekemkid** [comment]
The only real benefit I can see for a Trello is that as an outsider looking in, or someone looking to pluck some quick work, it would be very easy to see where we need work done. We would need Trello to aggregate all seneca-org issues. This would lead to a lot of bloat, but, make it easier to view the "full picture" bug wise, and get started.

**Comment by AdrieanKhisbe** [comment]
Indeed @thekemkid :+1:
The point of trello is to have global view and strategy. (prioritazing, allocating efforts), whereas github issues are for details, operational/tactical view.
Trello card are dynamics, and temporary, (status, short term chat), while github issue are there for more structured, longterm discussion. :)

(@mcdonnelldean I have very few label suggestion that I found missing, wher eshould I open the discussion)

**Comment by mcdonnelldean** [comment]
The real problem here is who manages this long term? There is an awful lot of work triaging this stuff on trello

**Comment by AdrieanKhisbe** [comment]
@mcdonnelldean that's a real question :)
In a way it's link to org communication, contributor synchronisation cf #158.
I have no problem being one of the person taking responsability that things run smoothly, and that the kanban is not stalled/unsynchronized 
:smiley:

**Comment by mcdonnelldean** [comment]
I'm just worried it's a big job. This is the sort of thing that starts well but nobody bothers using and it ends up becoming busy work.

**Comment by AdrieanKhisbe** [comment]
Legit concern ! :)
I'll say might be big, but if we create the dynamic will be less big, and shared. And few _guardian_ will watch to reignite the spirit when needed :) :wolf: :fire: 

“Let's experiment and adapt”. (but after nodeday, where we could talk about this :))

**Comment by mcdonnelldean** [comment]
@AdrieanKhisbe I'm going to close this out until after @naomifeehanmoran does her initial assessment of the org. I'd rather not talk about any of this until we get the very basics sorted first. Once that's done we can reopen, but right now it is just noise.

**Comment by AdrieanKhisbe** [comment]
ACK :confused:
