### ISSUE TITLE
CSS / HTML Overhaul

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/senecajs.org#181]
The current visual style of the site is fine and should not change, however the underlying template and css are pretty terrible, for example:

- Use of icon fonts
- Super heavy bootstrap markup
- Terrible mobile performance and layout 
- Terrible coloring of code boxes and inline code fragments
- Generally heavy, sluggish and in need of attention

## Notes

- Fonts need to be local or have some sort of fallback as use offline is a valid case
- We need to de emphasis the orange throughout the site, it's yucky.
- Structural changes that are required to improve the template are fine to do
- Auto builds on push to master. You can deploy to 'staging' via surge to test without being live
- Uses Sass (The stylus support in metalsmith is a bit pants)

**Comment by mcdonnelldean** [comment]
@thefoxis This is for next week. I'll mail you about it this afternoon.

**Comment by AdrieanKhisbe** [comment]
Idea, might be a good idea to replace boostrap by sematicUi.
http://semantic-ui.com/

(it's not because I went yesterday to [Paris.CSS meetup](https://twitter.com/CSSParis) that I am a css expert ^^)

**Comment by mcdonnelldean** [comment]
@AdrieanKhisbe :D @thefoxis Has done a lot of work for us already, it is in VERY capable hands.

**Comment by AdrieanKhisbe** [comment]
@mcdonnelldean No doubt about this! 
was just sharing a thought that came to my mind yesterday :smiley:

**Comment by mcdonnelldean** [comment]
Updated via #194 Final requests incoming

**Comment by mcdonnelldean** [comment]
Done :D
