### ISSUE TITLE
Update Contributors page with relevant links

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/senecajs.org#183]
@AdrieanKhisbe Your missing, @blainsmith your missing. Generally anyone that has a commit against the master branch of any of our projects (in org) should be on that list. 

@AdrieanKhisbe Do you at least want to add yourself and a few other high volume people?

**Comment by AdrieanKhisbe** [comment]
Noted, will do in the afternoon or tonight. :wink:

**Comment by blainsmith** [comment]
I'm not missing actually. I was added way back when https://github.com/senecajs/senecajs.org/commit/a69549b036377e46a4990d96eeb90b4613ecb764

**Comment by mcdonnelldean** [comment]
Oh you are :D Super, @AdrieanKhisbe I'd at least add you now, there is a blog post coming that mentions the page, get your name up in lights! The post is going out soon.

**Comment by AdrieanKhisbe** [comment]
_soon_, _soon soon_ or _soon soon soon_?
(minutes, hours, or days? :D)

**Comment by AdrieanKhisbe** [comment]
(dump the other name you think I should add, and I'll do at my next break)

**Comment by mcdonnelldean** [comment]
Hours :D Just you for now, I'll add the rest

**Comment by AdrieanKhisbe** [comment]
Noted sir!, Incoming!

**Comment by AdrieanKhisbe** [comment]
> _Voili Voilà Voilou_

cf cea20f7950b38b65d30fa32802f2132ae461ce88

**Comment by mcdonnelldean** [comment]
Super, I'll add others to the list here.

**Comment by AdrieanKhisbe** [comment]
@mcdonnelldean  Who else do we need to add along pixelastic?

**Comment by mcdonnelldean** [comment]
Um, 

@thefoxis 
@kamil-mech 

I think is it.

**Comment by AdrieanKhisbe** [comment]
will do in the coming hours. ping tomorrow if not done ;)
