### ISSUE TITLE
FAQ: senecajs mongostore configuration for slave db connection

### ISSUE THREAD

**Issue by som-soni** [senecajs/senecajs.org#184]
How do we configure mongo-store to connect to slave mongodb.

**Comment by AdrieanKhisbe** [comment]
(@som-soni -> might be better to ask this on the dedicated repositery)

(@senecajs/contributors -> we might need a maintener for mongo-store: pending PR, and issues)

**Comment by som-soni** [comment]
@AdrieanKhisbe thanks for your response. Following option while creating mongo-store works.

options:{
            readPreference : 'secondary'
       }
