### ISSUE TITLE
Create style guide

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/senecajs.org#200]
Hey @thefoxis I don't want all the hard work gone into this site to slowly drift. I think a style guide that we can refer back to means any changes to the style can be validated against it.

Also, What is the best way to do one of these were it is editable? I think it is important that we can evolve it too in the long term.

**Comment by thefoxis** [comment]
Closing here in favour of nearform/frontend-guide#1.

**Comment by AdrieanKhisbe** [comment]
The link is now broken. :/
@thefoxis , did you rename the repositery?

**Comment by thefoxis** [comment]
@AdrieanKhisbe — which link? I didn't rename any repositories.

**Comment by AdrieanKhisbe** [comment]
https://github.com/nearform/frontend-guide/issues/1 :/
I have a 404.
But maybe it's because the repo is not public.

**Comment by mcdonnelldean** [comment]
Repo is not yet public, just until there is something in it 😊

**Comment by AdrieanKhisbe** [comment]
Hehe 
> PUT https://github.com/nearform/frontend-guide
  some-magic

**Comment by AdrieanKhisbe** [comment]
psssssst, just heard about this:
https://twitter.com/zeplin_io
@thefoxis you might be interested into checking ;)
