### ISSUE TITLE
Typo (bug) in example

### ISSUE THREAD

**Issue by zpbappi** [senecajs/senecajs.org#203]
In [this](http://senecajs.org/tutorials/understanding-prior-actions.html) tutorial, the last example of the section [pattern-based apis makes this easy](http://senecajs.org/tutorials/understanding-prior-actions.html#pattern-based-apis-make-this-easy), it says:
```js
if (err) return respond(out)
```

I think, it should be:
```js
if (err) return respond(err)
```

**Comment by mcdonnelldean** [comment]
Correct! Good spot :D Do you want to open a little PR to change this?
