### ISSUE TITLE
We're using Seneca and it's great!

### ISSUE THREAD

**Issue by rr-appadaptive** [senecajs/senecajs.org#206]
[http://www.appadaptive.de](url)

**Comment by mcdonnelldean** [comment]
@rr-appadaptive Awesome stuff, if you can get us an svg of your logo we would be more than happy to put it on the site. Could you tell us a little about what you are building? I'm not familiar with German :(

**Comment by rr-appadaptive** [comment]
Hi Dean,

thanks for your prompt answer. To keep long things short, AppAdaptive is developing Apps for the german „Mittelstand“ (Keywords: Internet of things, Factory 4.0). whereas adaptive means that those apps are not only running on any device (if it has a browser) in a responsive way but are changing their functionality depending on user-roles, geo-location of the device, kind of device. The server side is realized with NodeJs, Seneca and others.

I’ve attached an SVG of our logo for your use.

Best Regards.

Regine Rosewich
— 
fon: +49-7645-9130-40
fax: +49-7645-9130-42
mo: +49-171-7791167
eM: regine.rosewich@appadaptive.de

AppAdaptive GmbH

Georgstr. 25

88212 Ravensburg

Tel.: +49 (751) 36605-0

Fax: +49 (751) 36605-20

________________________________________________________________

Handelsregister HRB 731 585 • Amtsgericht Ulm • Sitz der Gesellschaft: Ravensburg •

Geschäftsführung: Christian Steidle, Regine Rosewich


Diese E-Mail kann vertrauliche und/oder rechtlich geschützte 
Informationen enthalten. Wenn Sie nicht der richtige Adressat 
sind oder diese E-Mail irrtümlich erhalten haben, informieren 
Sie bitte den Absender und vernichten Sie diese E-Mail.
Das unerlaubte Kopieren sowie die unbefugte Weitergabe 
dieser E-Mail ist nicht gestattet. Soweit wir nicht vorsätzlich 
oder grob fahrlässig gehandelt haben, schließen wir jeden Schaden,
verursacht durch Computer-Viren aus dieser E-Mail oder ihren
Anhängen aus. Sie sollten in jedem Fall Ihre eigene Virenprüfung 
vornehmen, bevor Sie Anlagen aus dieser E-Mail öffnen. Vielen Dank.

This e-mail may contain confidential and/or privileged information. 
If you are not the intended recipient (or have received this e-mail 
in error) please notify the sender immediately and destroy this e-mail. 
Any unauthorized copying, disclosure or distribution on the material 
in this e-mail is strictly forbidden. We exclude liability for any damage 
caused by computer-viruses or the like insofar as we did not act willful 
or grossly negligent. We advise you to carry out your own Virus-Check 
before you open any of the attachments.

Von:  Dean McDonnell <notifications@github.com>
Antworten an:  "senecajs/senecajs.org" <reply@reply.github.com>
Datum:  Dienstag, 15. März 2016 15:54
An:  "senecajs/senecajs.org" <senecajs.org@noreply.github.com>
Cc:  Regine Rosewich <regine.rosewich@appadaptive.de>
Betreff:  Re: [senecajs.org] We're using Seneca and it's great! (#206)


@rr-appadaptive Awesome stuff, if you can get us an svg of your logo we would be more than happy to put it on the site. Could you tell us a little about what you are building? I'm not familiar with German :(

**Comment by mcdonnelldean** [comment]
@rr-appadaptive Hey, I just got back to this. The link doesn't attach because responding to these mails instead posts to Github. Could you send the image to `dean.mcdonnell@nearform.com` and I can personally put it up on the site for you :D

Awesome stuff! Sounds super interesting!

**Comment by mcdonnelldean** [comment]
@rr-appadaptive Logo now added :D http://senecajs.org/

If you have a link you would like me to hot link it to, let me know :tada:
