### ISSUE TITLE
The second argument of Bluebird's Promise.promisify should be an options-object since Bluebird v3.0

### ISSUE THREAD

**Issue by pioneer32** [senecajs/senecajs.org#207]
Approach to using Seneca with Promises, which is shown in Seneca's documentation, doesn't work with Bluebird v3.0 and higher as the Promisification API had been changed:

// Bluebird 2.x
Promise.promisify(fn, ctx);
// Bluebird 3.0
Promise.promisify(fn, {context: ctx});

So tutorial needs to be updated regarding this fact.
Thx )

**Comment by mcdonnelldean** [comment]
@pioneer32 The site auto updates on push to master, do you want to create a fix from the Github and I can accept it?

**Comment by pioneer32** [comment]
Sorry, I didn't notice. The note regarding Bluebird v3.0 already exists below the code block.
