### ISSUE TITLE
Unable to use senaca.make() method 

### ISSUE THREAD

**Issue by nkpathrut** [senecajs/senecajs.org#211]
I'm getting error as seneca.make() undefined not a function. I installed latest seneca package as well as verified the directory structure.

Still I'm facing the issue. Please help, I'm in the middle of water. As soon as possible I've implement micro-services example

**Comment by mcdonnelldean** [comment]
@nkpathrut hey, this is due to a change in `2.0.0`. We removed a the entity module as a default. It's super easy to fix, you just need to manually add the module, like so,

```
npm install seneca-entities --save
```

```
var seneca = require('seneca')()
seneca.use('entities')
```

From there make will work.

**Comment by nkpathrut** [comment]
var var1 = require('seneca')()

var product = var1.make('product')
product.name = 'Apple'
product.price = 1.99

// sends role:entity,cmd:save,name:product messsage
product.save$(console.log)

Would you provide the changes using entity here?

**Comment by mcdonnelldean** [comment]
The code above would be

```
var seneca = require('seneca')()

seneca.use('entity')

var product = seneca.make$('product')

product.name = 'Apple'
product.price = 1.99
product.save$(console.log)
```

assuming you also ran

```
npm install seneca-entity
```

**Comment by nkpathrut** [comment]
Thanksmcdonnelldean

**Comment by nkpathrut** [comment]
Thank you, mcdonnelldean!!! It works fine now. 

Would you like mention the documentation where I can find Updated Seneca guide of Micro-service Architecture Implementation?

**Comment by mcdonnelldean** [comment]
Great! Docs are something we are working on right now. Your best bet is probably to take a look around a working system. See, https://github.com/nodezoo/nodezoo-system

**Comment by mcdonnelldean** [comment]
I'm going to go ahead and close but feel free to make new issues if you get stuck.
