### ISSUE TITLE
I've created a plugin for Neo4j

### ISSUE THREAD

**Issue by paulnebel** [senecajs/senecajs.org#231]
Hi.  I'm the Co-founder and Technical Director of a startup called [RedJamJar](http://www.redjamjar.net).  We provide products and services related to knowledge sharing and management within organisations.  I've adopted Seneca as the framework of choice to support the microservices architecture I'm developing.  One of the significant aspects of the products we're creating is that they're based on graph databases.  I found a plugin for Neo4j but it was too out of date for me so I've created a [new one](https://github.com/redjamjar/seneca-neo4j-store).  Given that an NPM module already existed I've had to call mine seneca-neo4j2-store.  Not exactly snappy, but there you go.  It is released as open source and I'd like to contribute it to Senecajs.org if you are interested.  I know it says on your website to fork the repo and submit a pull request but I have to admit that I'm not clear as to which repo to fork.  I will be developing an equivalent plugin for OrientDB in the next month.

Please let me know (paul.nebel@redjamjar.net) if you are interested and, if so, how to proceed from here to incorporate in the Seneca ecosystem.

**Comment by mcdonnelldean** [comment]
This is epic. How would you feel about using the original name if I can get it made available. I'm prepping a release right now so snowed under but I will pick this up soon. Your module looks epic!

**Comment by paulnebel** [comment]
Hi Dean.  That would be absolutely fantastic!  I'm glad you like it.  As I
mentioned I'll be making a version for OrientDB as well.  I'm also
preparing a blog post to promote both the plugin and Seneca in general.

Thanks for the feedback.

Regards

Paul

On Fri, May 27, 2016 at 11:21 PM, Dean McDonnell <notifications@github.com>
wrote:

> This is epic. How would you feel about using the original name if I can
> get it made available. I'm prepping a release right now so snowed under but
> I will pick this up soon. Your module looks epic!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/senecajs/senecajs.org/issues/231#issuecomment-222266014>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AC1Zhh2Z3yQyRXkpTyWvlTyZCv4_vucYks5qF25jgaJpZM4Inp1v>
> .
>



-- 
Paul

-- 
Paul Nebel
Co-founder and Technology Director

*w*: www.redjamjar.net
*e*: paul.nebel@redjamjar.net
*m*: 07950 010 394
@redjamjar

**Comment by mcdonnelldean** [comment]
Sounds great!

I'll have someone look into improving the instructions for contribution to the site too. Looking over it the instructions are on the vague side and could do with being more explicit 

Kindest Regards,

Dean

**Comment by mcdonnelldean** [comment]
@piccoloaiutante How would you feel about @paulnebel taking ownership of https://github.com/piccoloaiutante/seneca-neo4j-store? See above.

**Comment by piccoloaiutante** [comment]
@mcdonnelldean i think it's a good idea. Let me know when to proceed with it.

**Comment by mcdonnelldean** [comment]
@piccoloaiutante Awesome stuff! I'd say go ahead and add me as admin. I will then work with @paulnebel to complete the transfer. Note you will need to give me npm rights also

**Comment by piccoloaiutante** [comment]
@mcdonnelldean i've added you in both account.

**Comment by mcdonnelldean** [comment]
Awesome stuff. @paulnebel My suggestion is to move this to your account then PR in your work, finally release a major version so as to not break previous versions.

This will allow you to use both the Github and NPM names as requested.

**Comment by paulnebel** [comment]
Hi.  Thanks very much for all your help so far.  As I understand it, you
want me to do the following:

   - Rename the redjamjar/seneca-neo4j-store repo as
   redjamjar/seneca-neo4j2-store (so as to leave redjamjar/seneca-neo4j-store
   available for the following operations)
   - Move the existing piccoloaiutante/seneca-neo4j-store code into the new
   redjamjar/seneca-neo4j-store
   - Submit and authorise a pull request from redjamjar/seneca-neo4j2-store
   to redjamjar/seneca-neo4j-store and bring my code in 'on top of' the
   existing code (with major version update)
   - Publish this new code to NPM
   - Delete redjamjar/seneca-neo4j2-store (which is now redundant)
   - Let you know when I've done that

I hope I've got that right.  Please feel free to correct me if I haven't.

Regards

Paul


On Mon, May 30, 2016 at 12:23 PM, Dean McDonnell <notifications@github.com>
wrote:

> Awesome stuff. @paulnebel <https://github.com/paulnebel> My suggestion is
> to move this to your account then PR in your work, finally release a major
> version so as to not break previous versions.
>
> This will allow you to use both the Github and NPM names as requested.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/senecajs/senecajs.org/issues/231#issuecomment-222471696>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AC1ZhlJQaCX5mBLgQfQvCM6Mr7RCjOmcks5qGsi_gaJpZM4Inp1v>
> .
>



-- 
Paul

-- 
Paul Nebel
Co-founder and Technology Director

*w*: www.redjamjar.net
*e*: paul.nebel@redjamjar.net
*m*: 07950 010 394
@redjamjar

**Comment by mcdonnelldean** [comment]
@paulnebel That is exactly it! There is not much point in us holding the name if you have a well maintained module that does it better 💃

**Comment by paulnebel** [comment]
Most excellent.  I'll get onto it now and let you know when I've done it.

Regards

Paul

On Mon, May 30, 2016 at 2:55 PM, Dean McDonnell <notifications@github.com>
wrote:

> @paulnebel <https://github.com/paulnebel> That is exactly it! There is
> not much point in us holding the name if you have a well maintained module
> that does it better 💃
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/senecajs/senecajs.org/issues/231#issuecomment-222497787>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AC1ZhkQiEHO85yg9q8WgpsH-XAYAo40eks5qGuxDgaJpZM4Inp1v>
> .
>



-- 
Paul

-- 
Paul Nebel
Co-founder and Technology Director

*w*: www.redjamjar.net
*e*: paul.nebel@redjamjar.net
*m*: 07950 010 394
@redjamjar

**Comment by paulnebel** [comment]
OK, I've updated the repo so that it now contains Michele's original code,
with my new code on top and a complete revision history for both.  The only
thing I can't do is to publish the NPM module as I don't appear to have
permission.  Could I be given permission to this package on NPM so that I
can push?

Thanks both,

Paul

On Mon, May 30, 2016 at 5:12 PM, Paul Nebel <paul.nebel@redjamjar.net>
wrote:

> Most excellent.  I'll get onto it now and let you know when I've done it.
>
> Regards
>
> Paul
>
> On Mon, May 30, 2016 at 2:55 PM, Dean McDonnell <notifications@github.com>
> wrote:
>
>> @paulnebel <https://github.com/paulnebel> That is exactly it! There is
>> not much point in us holding the name if you have a well maintained module
>> that does it better 💃
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/senecajs/senecajs.org/issues/231#issuecomment-222497787>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AC1ZhkQiEHO85yg9q8WgpsH-XAYAo40eks5qGuxDgaJpZM4Inp1v>
>> .
>>
>
>
>
> --
> Paul
>
> --
> Paul Nebel
> Co-founder and Technology Director
>
> *w*: www.redjamjar.net
> *e*: paul.nebel@redjamjar.net
> *m*: 07950 010 394
> @redjamjar
>



-- 
Paul

-- 
Paul Nebel
Co-founder and Technology Director

*w*: www.redjamjar.net
*e*: paul.nebel@redjamjar.net
*m*: 07950 010 394
@redjamjar

**Comment by mcdonnelldean** [comment]
Oops, let me get this sorted in the morning for you!

Kindest Regards,

Dean

**Comment by paulnebel** [comment]
Hi Dean

Could you please add me to the seneca-neo4j-store npm account so that I can
publish the plugin?

Thanks very much.

Paul

On Mon, May 30, 2016 at 6:40 PM, Dean McDonnell <notifications@github.com>
wrote:

> Oops, let me get this sorted in the morning for you!
>
> Kindest Regards,
>
> Dean
>
> > On 30 May 2016, at 18:30, Paul Nebel <notifications@github.com> wrote:
> >
> > OK, I've updated the repo so that it now contains Michele's original
> code,
> > with my new code on top and a complete revision history for both. The
> only
> > thing I can't do is to publish the NPM module as I don't appear to have
> > permission. Could I be given permission to this package on NPM so that I
> > can push?
> >
> > Thanks both,
> >
> > Paul
> >
> > On Mon, May 30, 2016 at 5:12 PM, Paul Nebel <paul.nebel@redjamjar.net>
> > wrote:
> >
> > > Most excellent. I'll get onto it now and let you know when I've done
> it.
> > >
> > > Regards
> > >
> > > Paul
> > >
> > > On Mon, May 30, 2016 at 2:55 PM, Dean McDonnell <
> notifications@github.com>
> > > wrote:
> > >
> > >> @paulnebel <https://github.com/paulnebel> That is exactly it! There
> is
> > >> not much point in us holding the name if you have a well maintained
> module
> > >> that does it better 💃
> > >>
> > >> —
> > >> You are receiving this because you were mentioned.
> > >> Reply to this email directly, view it on GitHub
> > >> <
> https://github.com/senecajs/senecajs.org/issues/231#issuecomment-222497787>,
>
> > >> or mute the thread
> > >> <
> https://github.com/notifications/unsubscribe/AC1ZhkQiEHO85yg9q8WgpsH-XAYAo40eks5qGuxDgaJpZM4Inp1v>
>
> > >> .
> > >>
> > >
> > >
> > >
> > > --
> > > Paul
> > >
> > > --
> > > Paul Nebel
> > > Co-founder and Technology Director
> > >
> > > *w*: www.redjamjar.net
> > > *e*: paul.nebel@redjamjar.net
> > > *m*: 07950 010 394
> > > @redjamjar
> > >
> >
> >
> >
> > --
> > Paul
> >
> > --
> > Paul Nebel
> > Co-founder and Technology Director
> >
> > *w*: www.redjamjar.net
> > *e*: paul.nebel@redjamjar.net
> > *m*: 07950 010 394
> > @redjamjar
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/senecajs/senecajs.org/issues/231#issuecomment-222532801>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AC1ZhlQ7rWZXpa4ISYN13LPdn5Z931ymks5qGyEbgaJpZM4Inp1v>
> .
>



-- 
Paul

-- 
Paul Nebel
Co-founder and Technology Director

*w*: www.redjamjar.net
*e*: paul.nebel@redjamjar.net
*m*: 07950 010 394
@redjamjar

**Comment by mcdonnelldean** [comment]
@paulnebel Appologies for the delay, what is your npm username?

**Comment by paulnebel** [comment]
Hi.

Thanks for getting back to me.  My NPM username is *DiscDoggy*.

Regards

Paul

On Thu, Jun 2, 2016 at 1:15 PM, Dean McDonnell <notifications@github.com>
wrote:

> @paulnebel <https://github.com/paulnebel> Appologies for the delay, what
> is your npm username?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/senecajs/senecajs.org/issues/231#issuecomment-223273850>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AC1ZhnJknPtuOYdIR3g0rmVRqyE3GrXFks5qHslIgaJpZM4Inp1v>
> .
>



-- 
Paul

-- 
Paul Nebel
Co-founder and Technology Director

*w*: www.redjamjar.net
*e*: paul.nebel@redjamjar.net
*m*: 07950 010 394
@redjamjar

**Comment by paulnebel** [comment]
Hi

Sorry to keep bugging you about this but I can't publish this npm module
until I have access to the seneca-neo4j-store npm account.  This is
starting to cause me issues as I have fixed several bugs in this code in
the last week and I don't really want to publish to my npm repo if it's
about to become deprecated.

I appreciate your help so far.

Regards

Paul

On Thu, Jun 2, 2016 at 3:16 PM, Paul Nebel <paul.nebel@redjamjar.net> wrote:

> Hi.
>
> Thanks for getting back to me.  My NPM username is *DiscDoggy*.
>
> Regards
>
> Paul
>
> On Thu, Jun 2, 2016 at 1:15 PM, Dean McDonnell <notifications@github.com>
> wrote:
>
>> @paulnebel <https://github.com/paulnebel> Appologies for the delay, what
>> is your npm username?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/senecajs/senecajs.org/issues/231#issuecomment-223273850>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AC1ZhnJknPtuOYdIR3g0rmVRqyE3GrXFks5qHslIgaJpZM4Inp1v>
>> .
>>
>
>
>
> --
> Paul
>
> --
> Paul Nebel
> Co-founder and Technology Director
>
> *w*: www.redjamjar.net
> *e*: paul.nebel@redjamjar.net
> *m*: 07950 010 394
> @redjamjar
>



-- 
Paul

-- 
Paul Nebel
Co-founder and Technology Director

*w*: www.redjamjar.net
*e*: paul.nebel@redjamjar.net
*m*: 07950 010 394
@redjamjar

**Comment by mcdonnelldean** [comment]
@paulnebel Apologies, should be corrected now.

**Comment by paulnebel** [comment]
Thank you very much for your help.  The plugin is now published to NPM.
I'm currently working on a tutorial on how to use the plugin with the User
plugin so as to take advantage of graphs.  I'll let you know as soon as
it's ready to be published.

Regards

Paul

On Tue, Jun 7, 2016 at 12:20 AM, Dean McDonnell <notifications@github.com>
wrote:

> @paulnebel <https://github.com/paulnebel> Apologies, should be corrected
> now.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/senecajs/senecajs.org/issues/231#issuecomment-224118002>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AC1ZhqMZJmMe35hFJHhuRgeIs6AjdshVks5qJKsygaJpZM4Inp1v>
> .
>



-- 
Paul

-- 
Paul Nebel
Co-founder and Technology Director

*w*: www.redjamjar.net
*e*: paul.nebel@redjamjar.net
*m*: 07950 010 394
@redjamjar

**Comment by mcdonnelldean** [comment]
@paulnebel Awesome stuff! I'm going to go ahead an close this so. Please feel free to PR senecajs.org and add it to the plugin list. 👍
