### ISSUE TITLE
document usage of paramspec agrument

### ISSUE THREAD

**Issue by k2s** [senecajs/senecajs.org#235]
the format `act(pattern [, paramspec], action)` is not mentioned in getting-start and also missing on page http://senecajs.org/api/#act-input-callback-

it is used for example in https://github.com/nodezoo/nodezoo-npm/blob/master/lib/npm.js#L107

the same problem is with documentation of `add(pattern [, paramspec], action)`

**Comment by mcdonnelldean** [comment]
@k2s Site is regenerating. The docs added should better explain it. paramspec was a terrible name. Doc's aren't completely finished but they are better.
