### ISSUE TITLE
get-started 404

### ISSUE THREAD

**Issue by rglenn-accenture** [senecajs/senecajs.org#253]
Looks like the getting started [page](http://senecajs.org/get-started/) is down..

**Comment by mcdonnelldean** [comment]
Ooops! My fault, I'll fix this shortly. The page is there, the links are wrong

http://senecajs.org/docs/tutorials/getting-started.html

**Comment by mcdonnelldean** [comment]
This has now been corrected. The live link is http://senecajs.org/getting-started/ and the button on the landing page is now corrected too. Closed via #255
