### ISSUE TITLE
app.use( seneca.export('web') ) throws an error

### ISSUE THREAD

**Issue by chessmonster** [senecajs/senecajs.org#266]
I'm a noob at seneca and I'm just trying to run sample codes from Developing Microservices with Node js, and it says:

```js
var seneca = require('seneca')();

seneca.add('role:api,cmd:bazinga',function(args,done){
    done(null,{bar:"Bazinga!"});
});

seneca.act('role:web',{use:{
    prefix: '/my-api',
    pin: {role:'api',cmd:'*'},
    map:{
    bazinga: {GET: true}
    }
    }})

var express = require('express');
var app = express();

app.use( seneca.export('web') ); // <<<<<< this line might be the cause 
app.listen(3000);
```

but Im getting an error that says:

```
TypeError: app.use() requires middleware functions
    at EventEmitter.use (/home/oem/node_modules/express/lib/application.js:209:11)
    at Object. (/home/oem/Documents/seneca/app.js:7:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

Also I tried to run another sample code copied from the web, I'm sorry I just can find the link. But I just copied, pasted and tried to run and I got the same error. I'm thinking this is more of a setup issue?

I'm still trying to play with this. The way I understand this is that on app.use line, basically I'm just calling the seneca-web module. so what I did was

> app.use(require('seneca-web'))

instead of

> app.use( seneca.export('web') )

then I ran node app.js, it ran the script with no error in the command. but when tried to access the module from a browser, then I got the error saying util is not found and is pointing to the seneca web file, which actually is from a call from seneca.

**Comment by chessmonster** [comment]
the sample code here also does not work.

https://github.com/senecajs-attic/getting-started/blob/master/app.js

**Comment by tresellefreshers2016** [comment]
can anyone please tell me the solution for above error

**Comment by tresellefreshers2016** [comment]
var seneca = require('seneca')()
 
seneca.add('role:api,cmd:bazinga',function(args,done){
done(null,{bar:"Bazinga!"});
});
seneca.act('role:web',{use:{
prefix: '/my-api',
pin: {role:'api',cmd:'*'},
map:{
bazinga: {GET: true}
}
}})
var express = require('express')
var app = express()
app.use( seneca.export('Web'))
app.listen(3000)


My error is:
D:\NodeJS\Seneca Frameowrk\seneca_with_express>node senecarest.js -log
{"kind":"notice","notice":"hello seneca yb9ixwy86436/1478584448657/4992/3.2.2/-","level":"info","when":1478584448693}
[]
D:\NodeJS\node_modules\express\lib\application.js:209
    throw new TypeError('app.use() requires middleware functions');
    ^

TypeError: app.use() requires middleware functions
    at EventEmitter.use (D:\NodeJS\node_modules\express\lib\application.js:209:11)
    at Object.<anonymous> (D:\NodeJS\Seneca Frameowrk\seneca_with_express\senecarest.js:16:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

can anyone please tell me the solution for this above error.


Thanks in advance

**Comment by nfantone** [comment]
@chessmonster and @tresellefreshers2016 
Moved to https://github.com/senecajs/seneca-web/issues/115
