### ISSUE TITLE
ALL ERRORS FATAL messages directs the developer to a broken link

### ISSUE THREAD

**Issue by jnhghy** [senecajs/senecajs.org#278]
Trying to run a senecajs project resulted in a FATAL ERROR message that directs me to http://senecajs.org/fatal.html for info but this page shows a 404 error, guess there should be a redirect there.

The full error message:
`ALL ERRORS FATAL: action called with argument fatal$:true (probably a plugin init error, or using a plugin seneca instance, see senecajs.org/fatal.html)`

**Comment by nfantone** [comment]
That URL was already removed and should not be around in the next release. Please see https://github.com/senecajs/senecajs.org/issues/236

**Comment by jnhghy** [comment]
@nfantone : sorry, didn't saw the other issue page, thanks for pointing it out.

**Comment by nfantone** [comment]
No problem! 🐐
