### ISSUE TITLE
FAQ: 

### ISSUE THREAD

**Issue by blueshirts** [senecajs/senecajs.org#286]
Since most seneca plugins seem to be named in the pattern 'seneca-some-plugin' how can you name the plugin in such a way that it read the plugin specific settings?

It is not possible to name the plugin using a function name.  Without this function name it seems like the plugin will not read the settings from the seneca.options.js file (even if you return 'seneca-some-plugin' from the function.

    module.exports = function seneca-some-plugin(options) {
        ...

Is there a way around this or do people have to name their plugins like my_plugin instead?

Also the seneca docs seem to indicate that the plugin name should be returned from the plugin as a string though I see many plugins using the following syntax.

    return {
        name: plugin
    }

What are the possible return options from the plugin?

**Comment by nfantone** [comment]
I've seen plugins return an object just like the one you describe and a simple string with the value for `name`.

```js
// This
return { name: 'my-plugin' };

// is the same as
return 'my-plugin';
```

I don't think there are any "official docs" for any of that, though.

**Comment by killerspaz** [comment]
Check this page out: http://senecajs.org/docs/tutorials/how-to-write-a-plugin.html

Talks about that some, but the gist is you can return the plugin name, or an object that defines some special properties, including `name`.

**Comment by ymohammad** [comment]
Hi,

I would like to know if seneca provides a way to interface a method which gets called after action method completes based on the pattern. Suppose, I have following patterns in my service.

'role:calculation, cmd:sum'
'role:calculation, cmd:product'
'role:calculation, cmd:division'

Is there any way I can register a call back function for the pattern ''role:calculation' which gets called once the response method called for the above given actions. Something like below.

```
this.SENECA_API_METHOD('role:calculation', function() {
    console.log("action calling completed");
});
```

**Comment by killerspaz** [comment]
You can register both patterns:

```
'role:calculation, cmd:sum'
'role:calculation, cmd:product'
'role:calculation, cmd:division'
'role:calculation'
```

When `cmd` is supplied it will contextualize (check out https://github.com/rjrodger/patrun) to the former ones, and without should match to the last pattern demonstrated.

In essence, you should be able to do:

```
seneca.add('role:calculation, cmd:sum', function() {
  seneca.act('role:calculation'); //calls your logging method
});
```

I haven't tried this in practice, but I do believe it should work. Alternatively, have a `cmd` dedicated to this logging approach.

**Comment by blueshirts** [comment]
The documentation does seem to indicate that you might drop the majority of your hyphenated name in favor of a short prefix.  I have been doing this and it seems to work.  I suppose if you have conflicts you can use the tag capability.

> There’s an obvious risk that you might have a naming conflict. Seneca allows this because it’s more useful to have the ability to override plugins. If you’re defining your own set of plugin names, it’s best to choose a short prefix for your project. This is a good idea in general for many frameworks!
> 
> For example, if you’re working on the Manhattan project, choose the prefix mh. Then call your “Trinity” plugin mh-trinity.

Also, I did find a very small fine print regarding returning an object out of the plugin.  I didn't see the additional referenced the comment speaks of though there was at least a mention of the object.  Seems like the two are somewhat equivalent if you don't have extra values to return. 

> (As an aside, note that you can also specify the name of the plugin by returning an object of the form {name:...}. You’ll see some more properties you can add this return object below).

Not sure where the extra values go.  That could possibly be expanded on.

**Comment by ymohammad** [comment]
Thanks @killerspaz for the answer. I think, I have not explained my question correctly. I would like to know if there is any Life cycle kind of method provided by Seneca which will gets called once the action method execution completed. It is like if I attached it to the action methods based through pattern. 

If I use the 'role:calculation' then this API method gets attached to all the patterns having role:calculation. Do we have any such feature in Seneca already available.

I know about the outward method but that is not linked for a pattern and it gets called multiple time if we use the Wrap. Please see the below code.

```
this.SENECA_API_METHOD('role:calculation', function() {
    console.log("action calling completed");
});
```

Plugin code. Here we have sub and wrap which gets called before invoking the action method. Do we have any existing method which gets called after completing the action method execution. 

```
module.exports = function math(options) {

  this.outward(function (ctxt, data) {
        console.log(">>>outword is called.. ");
  });

  this.add('role:math,cmd:sum, datatype:integers, variableCount:2', function sum(msg, respond) {
  	console.log(">>> called act method for variable 2 sum");
    respond(null, { answer: msg.left + msg.right })
  })

  this.add('role:math,cmd:sum, datatype:integers, variableCount:3', function sum(msg, respond) {
  	console.log(">>> called variable 3 sum");
    respond(null, { answer: msg.left + msg.right })
  })

  this.add('role:math,cmd:sum, datatype:integers, variableCount:4', function sum(msg, respond) {
    console.log(">>> called variable 4 sum");
    respond(null, { answer: msg.left + msg.right })
  })


  this.add('role:math,cmd:product', function product(msg, respond) {
    respond(null, { answer: msg.left * msg.right })
  })


  //Wrapper methods.. called for the patter matches..
  this.wrap('role:math, cmd:sum, datatype:integers', function (msg, respond) {
    console.log(">>> called wrap for pattern : role:math, cmd:sum, datatype:integers");
    this.prior(msg, respond)
  })

   this.wrap('role:math, cmd:sum', function (msg, respond) {
    console.log(">>> called wrap for pattern : role:math, cmd:sum");
    this.prior(msg, respond)
  })
   this.wrap('role:math', function (msg, respond) {
    console.log(">>> called wrap for pattern : role:math");
    this.prior(msg, respond)
  })

   //Subscription methods..Subscribe to a message pattern.
   // Works similar way of wrap. But this is called before wrap.
  this.sub('role:math*', function (err, msg) {
    console.log(">>> called sub for the pattern : role:math");
  })

  this.sub('role:math, cmd:sum', function (err, msg) {
    console.log(">>> called sub for the pattern : role:math, cmd:sum");
  })

  this.sub('role:math, cmd:sum, datatype:integers', function (err, msg) {
    console.log(">>> called sub for the pattern : role:math, cmd:sum, datatype:integers");
  })

  //Ready function called after calling act. It is a call back function plugin loading..
  this.ready(function() {
    console.log(">>> called the ready function..." + arguments.length);
  })
}
```

**Comment by nfantone** [comment]
@blueshirts I remembered that you can also define a `tag` property on the object returned from a plugin. It'll be used in log messages.

```js
  return {
    tag: 'plugin-tag',
    name: 'my-plugin'
  };
```

Seneca itself uses it to show its version number.

```sh
When: 2017-01-12T05:52:58.020Z

Log: {kind:null,plugin:seneca,tag:3.2.2,id:00ik6kjbzj8u/1484200377693/10084/3.2.2/-,code:transport_listen,notice:sen... }
```
