### ISSUE TITLE
Link to Getting started document in Github description is broken

### ISSUE THREAD

**Issue by amanagarwal2189** [senecajs/senecajs.org#305]
On the page https://github.com/senecajs-attic/getting-started, the link to Getting started is **http://senecajs.org/get-started/** which gives a '404'.

**Comment by nfantone** [comment]
@amanagarwal2189 You are correct. The proper link would be http://senecajs.org/getting-started/.

This should really be opened over at the [senecajs-attic](https://github.com/senecajs-attic/) repo, though. I'll do it for you.
