### ISSUE TITLE
Look at better fonts for headings

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/senecajs.org#49]
Right now the headings, menus and other large fonts are jaggy. We need to look at this and see can we improve it either by swapping the font or moving to a heavier set.

cc @AdrianRossouw

**Comment by robbdempsey** [comment]
little spacing makes it easier on the eye.  `letter-spacing: 1px;`

**Comment by mcdonnelldean** [comment]
@robbdempsey Awesome, in general or just the headings? How are you finding the body font?

**Comment by MikeZTaylor** [comment]
In general, I think we can add the line spacing. I'd also have a look at kerning but this is all to be done when we find the right font.

**Comment by AdrieanKhisbe** [comment]
> $ touch 

@mcdonnelldean,  Is it still needed, or has been fixed?

**Comment by mcdonnelldean** [comment]
Can be closed

Kindest Regards,

Dean
