### ISSUE TITLE
Document Seneca query syntax

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/senecajs.org#53]
A tutorial documenting Seneca's query syntax is needed. See below for example:

- `.list$({f1:v1, f2:v2, ...})` implies pseudo-query `f1==v1 AND f2==v2, ...`.

- `.list$({f1:v1,...}, {sort$:{field1:1}})` means sort by f1, ascending.

- `.list$({f1:v1,...}, {sort$:{field1:-1}})` means sort by f1, descending.

- `.list$({f1:v1,...}, {limit$:10})` means only return 10 results.

- `.list$({f1:v1,...}, {skip$:5})` means skip the first 5.

- `.list$({f1:v1,...}, {fields$:['fd1','f2']})` means only return the listed fields.

**Comment by kamil-mech** [comment]
Should we stick that under http://senecajs.org/tutorials/understanding-data-entities.html
or make a new tutorial?

**Comment by AdrieanKhisbe** [comment]
would rather say make a new one.

Ideally at some point we would have tutorial groups. (groupoing together the one about a similar subject)

**Comment by mcdonnelldean** [comment]
Yup lets go new, keep them small and focused.

**Comment by kamil-mech** [comment]
I'm trying to create a new page by replicating behaviour of an existing page.

However, markup doesn't work on my page. Am I missing something?

```
---
layout: main.html
---

# Understanding Query Syntax


## Subheading

aa

**bold**
```

![seneca a microservices toolkit for node js - mozilla firefox_001](https://cloud.githubusercontent.com/assets/10513845/12704768/f2f85e34-c859-11e5-8f07-7a71cf8bdbbb.png)

**Comment by kamil-mech** [comment]
My mistake. I named the file with `.html` extension, not `.md`

**Comment by kamil-mech** [comment]
Just to put it out there, I think `fields` isn't there anymore.

**Comment by mcdonnelldean** [comment]
Quite possibly :D It's been a while :D

**Comment by kamil-mech** [comment]
Too bad, it would be very powerful to have ^^

**Comment by mcdonnelldean** [comment]
There is some new magic coming soon to allow custom queries, not ready yet though.

**Comment by kamil-mech** [comment]
We need to double check the standards as well.

I remember few months back when I was working on CoderDojo, postgres store had utilities which other stores do not have.

**Comment by mcdonnelldean** [comment]
Agreed

**Comment by kamil-mech** [comment]
Should I self-assign in the future?

**Comment by mcdonnelldean** [comment]
@kamil-mech Please do :D

**Comment by kamil-mech** [comment]
Cool, no problem ^^
