### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Ava7** [senecajs/senecajs.org#54]
I was going to create a pull request, but then I realized I had some trouble finding the corresponding files so I decided to open an issue instead/first.

So, apparently, [the tutorial pages](https://github.com/senecajs/senecajs.org/tree/master/src/pages/tutorials) contain some links that lead to the old version of the website which now simply throw 404s (if that is even the page that is being used to generate the tutorials from). It is not so hard to find which links are troublesome since they are nicely left at the bottom of the `.md` pages, but the thing is that some of the lead to specific anchors. For instance, the first link at the bottom of `how-to-write-a-plugin.md` which looks like this `http://senecajs.org/api.html#long-m-add`. The anchor is absent and I couldn't actually find where the "api" pages is being generated from so I could create a new one.

P.S. There is also an extra closing square bracket at the end of the link called "Seneca Examples" in the tutorials index.

**Comment by mcdonnelldean** [comment]
@Ava7 Thanks for reporting this.

If you could list the ones you are having issues with I can look into them directly? The API doc gets autogenerated from the Seneca repo. It essentially downloads it on each build.

@geek @rjrodger We should probably get https://github.com/rjrodger/seneca/pull/172 commited so we can start allowing people to work on the API doc.

**Comment by mcdonnelldean** [comment]
@Ava7 Once 0.7 goes live (https://github.com/rjrodger/seneca/tree/0.7)

The API doc will be read from https://github.com/rjrodger/seneca/tree/0.7/docs

So to change it, a PR will need to be submitted there. It's slightly odd but we've found the need to include the api doc with the master repo and a need to keep it in sync with the site.

**Comment by Ava7** [comment]
@mcdonnelldean I see, that's what I thought initially but wasn't completely sure.

Let me give you an example with one of the links defined in [src/pages/tutorials/how-to-write-a-plugin.md](../tree/master/src/pages/tutorials/how-to-write-a-plugin.md); let's take a look at the first one `[_add_]: http://senecajs.org/api.html#long-m-add`. The anchor is no longer available, and I am not sure if the current one (which as you said is generated automatically) is reliable enough - `add-pattern-paramspec-action-`

If you think it is fine to use whatever has been spit out from the auto-generated pages, then I think I can send you a pull request. I just thought there might be a way to set these anchors manually and not worry that they might change without noticing.

**Comment by mcdonnelldean** [comment]
@Ava7 Awesome

So if you want to give this a shot here's how to do it:

1: Take a fork of seneca
2: Create a branch of 0.7, not master
3: Edit the api.md doc and add in what you think
4: Make a PR against the 0.7 branch
5: I'll review and merge it to the docs

Do you want to take a crack at it? I can support you if you need help

**Comment by Ava7** [comment]
@mcdonnelldean  Sorry for the double mention, I had to delete the branch and create it again.

I have fixed the links which I found to lead to nowhere, and also, I have removed some trailing white spaces which were hanging around the same files I happened to edit. One thing I couldn't figure out is where this link is supposed to lead -- "[guide to writing data store plugins]: /data-store-guide.html" from the file [/src/pages/tutorials/understanding-data-entries.md](https://github.com/Ava7/senecajs.org/blob/ca0877ac59fd9726ba5487ed2098b0ba1fc4c8d0/src/pages/tutorials/understanding-data-entities.md). Web archive hasn't caught it, have you got any idea what page it is supposed to bring the user to?

**Comment by mcdonnelldean** [comment]
@Ava7 Merged that in :D Thank you! Are there any more issues on this ticket to sort or are we good to close?

**Comment by Ava7** [comment]
@mcdonnelldean I believe we can close it for now. If I find some other broken links or something else I could re-open it again, or simply open a new one (luckily they are for free).

That's all for now, cheers! :beers:

**Comment by mcdonnelldean** [comment]
@Ava7 Awesome stuff :+1: Thanks :D
