### ISSUE TITLE
There are quite a few seneca talks out there - need a page listing them

### ISSUE THREAD

**Issue by rjrodger** [senecajs/senecajs.org#55]
lots from me obviously, but also a few others
would really help people to get wider context

**Comment by mcdonnelldean** [comment]
Agreed,

They also have nuggets of info in them that would form the basis of good docs. At least for your ones Richard, can you provide links? I'll go a searching on tinterwebz for others and list them here.

**Comment by mcdonnelldean** [comment]
@code-jace I think we have found a job for ya :D

Basically we need you to go to Vimeo / YouTube and find any talks by Richard and co on Seneca and Microservices in general. I'd like to do a curated list of this content so as you find ones, simply pop the links on this issue and we will go from there.

**Comment by code-jace** [comment]
## YouTube ##
Richard Rodger - Microservices
https://www.youtube.com/watch?v=fVfWuked2qE

Microservices Dublin (February 2015): Richard Rodger "Measuring Microservices"
https://www.youtube.com/watch?v=ZRBKfyykEw8

Richard Rodger - Measuring Micro-services - Codemotion Rome 2015
https://www.youtube.com/watch?v=SQYCzAWlrHU

Richard Rodger - "How Microservcies fail and what to do about it"
https://www.youtube.com/watch?v=f40EybJwgBo

Richard Rodger talking at first ever microservices Dublin meetup
https://www.youtube.com/watch?v=312zVGIHp9o

still looking

**Comment by code-jace** [comment]
Richard Rodger (2013, IDK)
https://www.youtube.com/watch?v=Qv0VQf7iJGQ

**Comment by mcdonnelldean** [comment]
@code-jace Awesome, I'll talk to you personally about getting this stuff on to a page. I want to quickly review them first. Also check Vimeo for both Seneca and Richard. 

@rjrodger Where do you normally host your slides?

@mcollina @pelger Are any if your talks about Seneca?

**Comment by ckiss** [comment]
@mcdonnelldean this task was assigned to me by Wyatt. I will write on the slack channel and ask anybody to provide any links they have containing seneca talks.

**Comment by ckiss** [comment]
More Links with seneca talks/slides:
- Dean @ Node.js Dublin 26th Nov 2015: http://pattern-matching-is-awesome.mcdonnelldean.me
- Richard @ Node.js Dublin 16 Aug 2012: http://www.slideshare.net/rjrodger/introducing-the-seneca-mvp-framework-for-nodejs

**Comment by mcollina** [comment]
"We are not Object-Oriented anymore" - https://skillsmatter.com/skillscasts/6819-we-are-not-object-oriented-anymore-or-why-the-node-callback-style-is-awesome#showModal?modal-signup-complete
slides: https://github.com/mcollina/we-are-not-object-oriented-anymore-demo
writeup: http://thenewstack.io/microservices-node-js/
