### ISSUE TITLE
are we linking to seneca-examples?

### ISSUE THREAD

**Issue by rjrodger** [senecajs/senecajs.org#56]
lots of good stuff there for learning

**Comment by mcdonnelldean** [comment]
@rjrodger We are but there are a couple of different repos that need to be merged and cleaned as the canonical Examples repo. This is my weekend task so any repo's you own that are just samples add me too them and I will start merging them all together and improving.

**Comment by SteveALee** [comment]
There's a link to https://github.com/senecajs/seneca-examples on http://senecajs.org/tutorials/ and that is 404

**Comment by geek** [comment]
@rjrodger can you move seneca-examples to /senecajs

**Comment by AdrieanKhisbe** [comment]
done cf http://senecajs.org/tutorials/
