### ISSUE TITLE
getting started part 2

### ISSUE THREAD

**Issue by SteveALee** [senecajs/senecajs.org#71]
The getting started guide is excellent, one of the best Image read.

It would-be really usefull to go the next step you hint at and outline how you might use Docker. Also an outline full microservices dev. and deploy workflows would be a great help. 

Or maybe that is the subject for blogs or a book? :)

**Comment by mcdonnelldean** [comment]
@SteveALee Thanks for the comments. We actually do have a workshop around using Seneca with seneca and some other popular libs. see https://github.com/nearform/msworkshop

There is a bit of work to do on it before it's ready for non instructor led use. But for now you should be able to see how it all fits together.

**Comment by SteveALee** [comment]
@mcdonnelldean any clues how to get the 2 image .tar files? I couldn't find nearForm on the Docker Hub.

**Comment by mcdonnelldean** [comment]
@SteveALee For that particular workshop they are just pulled off docker hub:

- nodejs offical
- tutum/influxdb

Do not that there is still some work to be done on that workshop.

**Comment by SteveALee** [comment]
@mcdonnelldean Ah OK thanks. There were many of each listed. I realised I may not get far but fancied a play :)
