### ISSUE TITLE
Minor getting-started documentation bugs

### ISSUE THREAD

**Issue by ianhoolihan** [senecajs/senecajs.org#88]
Very minor: in the 'writing microservices' section of http://senecajs.org/get-started/, it states:

> ... to the math-service microservice above, which then responds with:
`{ "answer":2 }`

And I believe it should be 3, not 2.

**Comment by ianhoolihan** [comment]
Also,

> Let’s put all this together into an example that sends role:math messages out over TCP on port 30303 (just an arbitrary port) and executes all other messages locally.
First, the listening service (math-plugin.js):

That last link should (I think) be math-pin-client.js, I believe.

**Comment by mcdonnelldean** [comment]
Thanks @ianhoolihan you look correct on both counts, I will get these looked at today. I'll close the issue when done so you know its ready.
