### ISSUE TITLE
link to seneca-docs at end of /plugins/ page is broken

### ISSUE THREAD

**Issue by boneskull** [senecajs/senecajs.org#91]
title says it all

**Comment by mcdonnelldean** [comment]
@boneskull Awesome! Thanks for the ping on this. I'll get it looked at :D

**Comment by boneskull** [comment]
I was looking for the  "How to Write a Plugin" doc and was having trouble finding it as well.  I see it referenced in various places but most of the links I found were broken.

**Comment by boneskull** [comment]
(luckily there's not a hell of a lot to know w/r/t writing a plugin)

**Comment by mcdonnelldean** [comment]
@boneskull So first issue fixed. I'll look into the others tomorrow for you.
