### ISSUE TITLE
When plugin syntax is wrong the document url is sending to 404

### ISSUE THREAD

**Issue by mirceaalexandru** [senecajs/senecajs.org#98]
Try to use a plugin with a wrong syntax:

module.exports = function( seneca, options, callback )

Seneca will die with following message:
.....
ns, callback ) { ... }. The correct format is: function(options) { ... }. For more details, please see http://senecajs.org/write-a-plugin.html

The url for details is not valid, it sends to 404 page.

I think it should be
http://senecajs.org/tutorials/how-to-write-a-plugin.html

**Comment by mcdonnelldean** [comment]
@mirceaalexandru Where is this?

**Comment by mirceaalexandru** [comment]
Seneca is dying with that message. Part of the message is that for details that documentation page should be accessed, and that url is not valid anymore. I did not search for that as I was in that moment forced to fix something else. Tomorrow I will check and create a PR

**Comment by mcdonnelldean** [comment]
Ah! Yeah a pr would be awesome @geek can approve it.

**Comment by mirceaalexandru** [comment]
Fixed by 
https://github.com/senecajs/seneca/commit/1612a384931e6e4ece9f2ef30515d4335ab6b7c7
